# Generated by Django 3.0.2 on 2020-03-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_lastworn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastworn',
            name='date',
            field=models.DateField(verbose_name='date last worn'),
        ),
    ]
