# Generated by Django 3.0.2 on 2020-03-18 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200318_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lastworn',
            options={'ordering': ['-date']},
        ),
    ]
